site_name: humid Docs
repo_url: https://github.com/h0uter/humid # backlink to repo
repo_name: humid # name to display on backlink to repo

nav:
  - index.md

plugins:
  - search # search box
  - mkdocstrings # generate documentation from Google Docstrings

theme:
  name: material # use the mkdocs-material theme
  logo: assets/logo.png

  ###  Everything after this is Optional ###
  palette: # enable dark mode toggle
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social: # add contact buttons at the bottom of the page
    - icon: material/email
      link: mailto:houterm+humid@gmail.com

copyright: Copyright &copy; Wouter Meijer
