[project]
name = "humid"
version = "0.1.0"
description = "Human Friendly UUIDs that are readable and pronounceable."
authors = [{ name = "W. Meijer", email = "houterm+humid@gmail.com" }]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }
keywords = [
    "readable",
    "UUID",
    "ID",
    "human friendly",
    "pronouncable",
    "adjective",
    "word",
    "noun",
    "generate",
]
classifiers = ['Programming Language :: Python :: 3']

[project.optional-dependencies]
dev = ["pytest>=8.3.2", "pre-commit>=3.5.0"]
docs = ["mkdocs-material>=9.5.33", "mkdocstrings-python>=1.10.9"]


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
build.package-dir = "src"
